version: '3.4'

services:
  inventoryservice:
    image: inventoryservice
    ports:
      - "5001:80"
    environment:
      - JWT_KEY=JwbpmiLG3W2l/V3LO+caAC5v3iQigIIIQKbbcp0p3PU=

  userservice:
    image: userservice
    ports:
      - "5002:80"
    environment:
      - JWT_KEY=JwbpmiLG3W2l/V3LO+caAC5v3iQigIIIQKbbcp0p3PU=

  orderservice:
    image: orderservice
    ports:
      - "5003:80"
    environment:
      - JWT_KEY=JwbpmiLG3W2l/V3LO+caAC5v3iQigIIIQKbbcp0p3PU=

  productservice:
    image: productservice
    ports:
      - "5004:80"
    environment:
      - JWT_KEY=JwbpmiLG3W2l/V3LO+caAC5v3iQigIIIQKbbcp0p3PU=

  transactionservice:
    image: transactionservice
    ports:
      - "5005:80"
    environment:
      - JWT_KEY=JwbpmiLG3W2l/V3LO+caAC5v3iQigIIIQKbbcp0p3PU=
